From OmniOS

This test tries to set a file date to 2108-12-30.
On illumos, the os.utime() call raises:
	OSError: [Errno 79] Value too large for defined data type

diff -wpruN '--exclude=*.orig' a~/Lib/test/test_zipfile.py a/Lib/test/test_zipfile.py
--- Python-3.12.1/Lib/test/test_zipfile/test_core.py.~1~	Thu Dec  7 12:45:44 2023
+++ Python-3.12.1/Lib/test/test_zipfile/test_core.py	Mon Feb  5 12:03:34 2024
@@ -622,7 +622,7 @@
             self.skipTest(f'time.localtime({ts}) raises OverflowError')
         try:
             os.utime(TESTFN, (ts, ts))
-        except OverflowError:
+        except (OverflowError, OSerror):
             self.skipTest('Host fs cannot set timestamp to required value.')
 
         mtime_ns = os.stat(TESTFN).st_mtime_ns
